### PR TITLE
Fix -ignore-config flag behavior

### LINKED ISSUE #8: The -ignore-config command line option will never work
**Describe the bug**
Currently the program, when running on Windows, always uses default configuration, because of another bug (there is no `HOME` environment variable on Windows, so it will never find the configuration file). 
The `-ignore-config` option is seems intended to use the default configuration even if the custom user configuration is found. But it will never work, because in the code the value of the corresponding variable is checked **before**  call to `flag.Parse()`

**To Reproduce**
1. Create a valid configuration file in a proper place
2. Run the program with `-ignore-config`
3. The default configuration will not be loaded

**Expected behavior**
Specifying `-ignore-config` in the command line should lead to use the default configuration.

**Environment (please complete the following information):**
 - OS: Linux and MacOS (will not reproduce on Windows because of other bug)
 - Go Version: `any`
 - Shell: `any`

### PR DESCRIPTION
**Pull request by nikitar020**
## Description

Previously, the `-ignore-config` command-line flag was not working. Now it works according to the following logic:

- If the `-ignore-config` is specified then the built-in configuration defaults are used, else Aminal tries to load configuration file.
- The parameters `-shell`, `-debug`, and `-slomo` are actually overriding corresponding values specified in the configuration (whether default or loaded from a configuration file).

Fixes #8 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- Run Aminal without parameters to ensure the default configuration file is created, and then close.
- Edit `%USERPROFILE%\.config\aminal\config.toml` and change `shell` parameter to `"cmd.exe /K echo test"`.
- Run Aminal without parameters again and see the `test` text at the top of the Aminal window. That proves that it uses the shell specified in the configuration file. Close Aminal.
- Run Aminal with `-shell cmd.exe` parameter. Now there will be no `test` message. This proves that the `shell` configuration parameter has been overridden. Close Aminal.
- Run Aminal with `-ignore-config` parameter. Again, there will be no `test` message. This proves that the entire configuration file has been ignored and the built-in default configuration has been used.

**Test Configuration**:
* OS: `Windows`
* OS version: `10`
* Go version: `go1.11.2 windows/amd64`

### CODE REVIEW

File: config.go [hunk 1]
```diff
@@ -9,26 +9,33 @@ import (
...
+	"strings"
 )
 
-func getConfig() *config.Config {
+func isFlagProvided(flagName string) bool {
+	result := false
 
-	showVersion := false
-	flag.BoolVar(&showVersion, "version", showVersion, "Output version information")
+	flag.Visit(func(f *flag.Flag) {
```
Comment (MaxRis) [inline config.go]: @nikitar020  Does it have more sense here to call `flag.Lookup` instead? For example, just
```
return flag.Lookup(flagName) != nil
```

Comment (nikitar020) [reply config.go]: That will not work because `flag.Lookup()` searches through _formal_ (i.e. defined) parameters, not _actually provied_. 
So, for example, `flag.Lookup("version")` will return non-nil value even if the `-version` parameter is not present in the command line.

See https://stackoverflow.com/a/40012425 for additional info.
